### ISSUE TITLE
emoji bug

### ISSUE THREAD

**Issue by jesusvallez** [tecfu/tty-table#16]
Hello everyone!

I have a problem with Windows and emoji =S

![image](https://cloud.githubusercontent.com/assets/19146593/25775908/a7ddf0d6-32b0-11e7-951a-79d752e7332e.png)

How can I fix it?

**Comment by tecfu** [comment]
I think this has to do with the way wide characters are currently identified. Can you reply with the unicode for the emoji you tried to use?

**Comment by jesusvallez** [comment]
LordPablo\u26A1\uFE0F (LordPablo⚡️)

This is the real string:
![image](https://cloud.githubusercontent.com/assets/19146593/25776683/c515560c-32c5-11e7-994a-eb38824acf20.png)

I am removing all the emojis because if I print them I get the deformed table

**Comment by tecfu** [comment]
I don't know precisely what's up with this because I don't have Windows. But I decided to write my own [word wrap package](https://www.npmjs.com/package/smartwrap) after this issue was raised so that this is avoided automatically in the future. 

The wrap seems to work now, but if you could test it and let me know if you continue to have problems I'd appreciate it.
