### ISSUE TITLE
No support for "" or '' wrapped strings 

### ISSUE THREAD

**Issue by foxinni** [tecfu/tty-table#17]
Hi,

I can't seem to parse a CSV with strings containing commas. Like so...

```security,price
aapl,"Hello, World"
ibm,"120,15"
```
Great idea otherwise.

**Comment by tecfu** [comment]
This works as of the latest release. 

The way that CSV is consumed is due to the behavior of a dependency, node-csv-parse. [I found a closed ticket for a similar issue and tested it and your example below.](https://github.com/wdavidw/node-csv-parse/issues/48)

To change the way that **tty-table** consumes csv, you can use the options listed [here](http://csv.adaltas.com/parse/). Custom options can be specified with the "csv-" prefix like so:

```
cat somefile.csv | node tty-table --csv-delimiter=";" --csv-escape="'"
```

- Inline Example

```sh
echo 'aapl,"Hello, World"'$'\n''ibm,"120,15"' | node src/terminal-adapter.js
┌───────────────────┬───────────────────┐
│       aapl        │   Hello, World    │
├───────────────────┼───────────────────┤
│        ibm        │      120,15       │
└───────────────────┴───────────────────┘
```

- Redirect Example

```sh
cat examples/data/delimiter-inside-quoted-fields.csv | node src/terminal-adapter.js
┌───────────────────┬───────────────────┐
│       aapl        │   Hello, World    │
├───────────────────┼───────────────────┤
│        ibm        │      120,15       │
└───────────────────┴───────────────────┘
```

- [Semicolon Delimited Example](https://github.com/wdavidw/node-csv-parse/issues/48#issue-85152916) 

```sh
echo '"foo";"bar"'$'\n''"lol;cat";"barf"' | node src/terminal-adapter.js --csv-delimiter=';' 
┌───────────────────┬───────────────────┐
│        foo        │        bar        │
├───────────────────┼───────────────────┤
│      lol;cat      │       barf        │
└───────────────────┴───────────────────┘
```

**Comment by tecfu** [comment]
This works as of [version 2.4.0](https://www.npmjs.com/package/tty-table).

The way that CSV is consumed is due to the behavior of a dependency, node-csv-parse. [I found a closed ticket for a similar issue and tested it and your example below.](https://github.com/wdavidw/node-csv-parse/issues/48)

To change the way that **tty-table** consumes csv, you can use the options listed [here](http://csv.adaltas.com/parse/). Custom options can be specified with the "csv-" prefix like so:

```
cat somefile.csv | node tty-table --csv-delimiter=";" --csv-escape="'"
```

- Inline Example

```sh
echo 'aapl,"Hello, World"'$'\n''ibm,"120,15"' | node src/terminal-adapter.js
┌───────────────────┬───────────────────┐
│       aapl        │   Hello, World    │
├───────────────────┼───────────────────┤
│        ibm        │      120,15       │
└───────────────────┴───────────────────┘
```

- Redirect Example

```sh
cat examples/data/delimiter-inside-quoted-fields.csv | node src/terminal-adapter.js
┌───────────────────┬───────────────────┐
│       aapl        │   Hello, World    │
├───────────────────┼───────────────────┤
│        ibm        │      120,15       │
└───────────────────┴───────────────────┘
```

- [Semicolon Delimited Example](https://github.com/wdavidw/node-csv-parse/issues/48#issue-85152916) 

```sh
echo '"foo";"bar"'$'\n''"lol;cat";"barf"' | node src/terminal-adapter.js --csv-delimiter=';' 
┌───────────────────┬───────────────────┐
│        foo        │        bar        │
├───────────────────┼───────────────────┤
│      lol;cat      │       barf        │
└───────────────────┴───────────────────┘
```

**Comment by tecfu** [comment]
For whatever reason, the example you gave didn't require any additional csv-* arguments in order to run correctly under tty-table > version 2.4.0.
