### ISSUE TITLE
infinite loop in line wrapping

### ISSUE THREAD

**Issue by mscalora** [tecfu/tty-table#51]
# Problem Summary

infinite loop in line wrapping when wide char are not handled correctly

## Expected Result (screen shot if possible)

program terminating

## Actual Result (screen shot if possible)

program never terminates

## Environment Information 

 * OS: Mac

 * Terminal Emulator: iTerm

## Steps to Reproduce 

 1. run this from examples folder:
```
    const Table = require("../")
    
    process.stdout.columns = 25
    
    console.log("Starting... (user CTRL-C to give up)")
    console.log("\"fix\" by uncommenting line format.js:70")
    
    let output = new Table([
      {minWidth: 6, shrink: 0},
      {minWidth: 12, shrink: 1},
      {minWidth: 24, shrink: 1000}
    ], [[
      "aaa bbb ccc",
      "aaa bbb ccc ddd eee fff ggg hhh",
      "aaa bbb ccc ddd eee fff ggg hhh iii jjj kkk lll mmm nnn ooo ppp qqq rrr sss ttt"
    ], [
      "汉堡包",
      "特制的酱汁",
      "2玉米饼, 大米和豆类, 大米和豆类, 大米和豆类, 奶酪"
    ]], {
      paddingLeft: 0,
      paddingRight: 0,
      marginTop: 0
    }).render()
    
    console.log(output)
```

Note: uncommenting line format.js:70 prevents the infinite loop, it appears that the wide char detection is not working correctly. I'm not sure why the detation was changed to the RegExp, the commit message does not explain. Performance perhaps?

**Comment by tecfu** [comment]
Problem:
---

In this scenario, a column has an inferred width of 1 but contains a special character that is 2 terminal spaces wide. 

I created this bug by removing the minimum column width requirement of 2 when wrapping text in #50. That made text extend one space when column widths are set to 1.

How to best handle this? 

Options:
---

1. Default to a minimum column width of 2 so that wide values can be wrapped

  - That would yield an unexpected default output in cases where a column contains row values of a single character. One would expect the row to be a single column.

  - When overriden to a minimum width of 1, each row would have to be checked for a wide character. This becomes problematic when piping data `my-stream.js | tty-table`. Streamed tables are currently set to maintain constant column widths as data changes. 

 - This would still fail in the event of single wide character widths > 2.

- This would still fail if the user sets the column width to 1 but has wide character values in the column. 

2. Show a 1 character wide error placeholder instead of attempting to resize for the wide character

- Would not fail in the cases noted above

- Could use the default error placeholder. 

- Could add a logical test in the wrap method to make sure not attempting to wrap a value in impossibly narrow width, if true replace value with error placeholder.

Solution:
---

I'm going to implement option 2, unless @mscalora  has a better idea.

**Comment by mscalora** [comment]
I think the error placeholder is the correct thing when a single char can't fit on the line, in the future the column minWidth should prevent that in most cases.
